### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by pi8027** [math-comp/algebra-tactics#34]
- I'd like to put a paragraph in README that makes clear the source of `Lemma from_sander` and its relation to elliptic curves. I also suggest separating this example to `from_sander.v`. @amahboubi, Could you take care of the former part? (I mean, could you write down a paragraph explaining these points?)
- I'd like to indicate there were significant contributions by @gares and @amahboubi. I'm fine to include both of you as coauthors. Otherwise, I'd like to put a paragraph in README to give you credit. What do you think?

**Comment by gares** [comment]
Give me credit in the readme, or nothing at all (github already says I did contribute a few commits)

**Comment by amahboubi** [comment]
I have no strong opinion about where to put credit.

**Comment by amahboubi** [comment]
Where would you like me to write something about the "large" example?

**Comment by pi8027** [comment]
> Where would you like me to write something about the "large" example?

@amahboubi Please write that as a comment here. Then I will reflect it to the [last section of README](https://github.com/math-comp/algebra-tactics#credits).

**Comment by amahboubi** [comment]
This example was given to me by [Sander Dahmen](http://www.few.vu.nl/~sdn249/). It is related to a computational proof that elliptic curves are endowed with a group law. As [suggested](https://hal.inria.fr/inria-00129237v4/document) by @thery a while ago, this problem is a good benchmark for proof systems. Laurent Théry and Guillaume Hanrot formally verified this property in Coq in 2007, see the [paper](https://doi.org/10.1007/978-3-540-74591-4_24).

**Comment by thery** [comment]
good does this mean that II will soon be able to move my elliptic proof to mathcomp :smile: ?

**Comment by pi8027** [comment]
@amahboubi Thanks. I updated README in #51 (based on your comment, with slight modifications).

@thery I hope so, although I don't have time to check that at the moment. BTW, isn't it already done in [elliptic-curves-ssr](https://github.com/strub/elliptic-curves-ssr)?

**Comment by thery** [comment]
@pi8027 no Pierre Yves's proof is a completly different one,

**Comment by thery** [comment]
@pi8027 do you support `ring[H1 .. Hn]` and `field[H1 .. Hn]`?

**Comment by thery** [comment]
@pi8027 Just did the port from of the [elliptic file](https://github.com/thery/coqprime/blob/master/src/Coqprime/elliptic/SMain.v) in Coprime to its [mathcomp equivalent](https://github.com/thery/mathcomp-extra/blob/master/elliptic.v) with your tactics.  This is pretty intensive (~50 calls to `field`). 
It works pretty well :fireworks: but it is a bit slower :disappointed:
Before 

```
real	0m7.975s
user	0m7.641s
sys	0m0.310s
```
with mathcomp
```
real	0m22.157s
user	0m21.680s
sys	0m0.402s
```
Did you already notice this kind of slow down?

**Comment by pi8027** [comment]
@thery I thought Algebra Tactics are slower than the original `ring` and `field` tactics because of conversion checking and preprocessing, but do not think x3 slowdown is a reasonable price to pay. I have some potential ways to *mitigate* this slowdown. But, it will never be faster than the original `ring` and `field` tactics, and I do not have time to try them right now.

Anyway, could you open a new issue for this? I will think about it later.
