### ISSUE TITLE
Support for `nat` ?

### ISSUE THREAD

**Issue by amahboubi** [math-comp/algebra-tactics#40]
```coq
From mathcomp Require Import all_ssreflect all_algebra.
From mathcomp Require Import ring.

Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.

Lemma doo (n m : nat) : m + n = n + m.
Fail ring.
```

Is `ring` supposed to eventually work for type `nat` ? For semi-rings in general? Note that `ring` does not fail if we remove the `Require Import ring` line.

**Comment by pi8027** [comment]
For natural numbers, I would recommend using `lia` instead for now. However, we will eventually be able to add the semiring structure to the hierarchy (MathComp 2.0 required), and then it makes sense to implement a tactic for semirings.

**Comment by pi8027** [comment]
Aha, but `ssrnat` adapts `ring` to `nat` equations. So this is indeed bad.

**Comment by amahboubi** [comment]
But may be could we consider changing this in `ssrnat`.
