### ISSUE TITLE
Since there is a version 1.0.0 - should it move in Coq Platform from "extened" to "full"?

### ISSUE THREAD

**Issue by MSoegtropIMC** [math-comp/algebra-tactics#66]
I saw that there is a version 1.0.0 now.

This opens the question if this package should be moved from the Coq Platform "extended" to the "full" level in Coq Platform 2022.09.

The main difference is that packages in the "full" level are expected to have a reasonably stable API. That is changes which would lead to major incompatibilities (frequent and/or not trivial to fix) are not expected.

**Comment by pi8027** [comment]
@MSoegtropIMC Thanks for reminding me of this. I would say it should be moved to the "full" level.
